version: '3.8'
services:
  api:
    container_name: chat_app_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - chat_app_net

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - chat_app_net

  redis:
    image: redis/latest
    ports:
      - "6379:6379"

volumes:
  postgres:
    name: nest-db

networks:
  chat_app_net:
    name: Chat App Networks
    driver: bridge
